// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id)
VALUES ($1, $2, $3, NOW(), NOW(), $4, $5, $6)
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id
`

type CreateSessionParams struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	UserID    string           `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM session WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE token = $1
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSession, token)
	return err
}

const getGitHubInstallation = `-- name: GetGitHubInstallation :one
SELECT id, github_installation_id, account_login, account_id, account_type, created_at FROM github_installations WHERE github_installation_id = $1
`

func (q *Queries) GetGitHubInstallation(ctx context.Context, githubInstallationID string) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubInstallation, githubInstallationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT s.id, s.expires_at, s.token, s.created_at, s.updated_at, s.ip_address, s.user_agent, s.user_id, u.name, u.email, u.image
FROM session s
JOIN "user" u ON s.user_id = u.id
WHERE s.token = $1 AND s.expires_at > NOW()
`

type GetSessionByTokenRow struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	UserID    string           `json:"user_id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Image     pgtype.Text      `json:"image"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.Image,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, email_verified, image, created_at, updated_at FROM "user" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, email_verified, image, created_at, updated_at FROM "user" WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGitHubInstallations = `-- name: ListGitHubInstallations :many
SELECT id, github_installation_id, account_login, account_id, account_type, created_at FROM github_installations ORDER BY created_at DESC
`

func (q *Queries) ListGitHubInstallations(ctx context.Context) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listGitHubInstallations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubInstallation{}
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.GithubInstallationID,
			&i.AccountLogin,
			&i.AccountID,
			&i.AccountType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGitHubInstallation = `-- name: UpsertGitHubInstallation :one
INSERT INTO github_installations (github_installation_id, account_login, account_id, account_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_installation_id) DO UPDATE SET
    account_login = EXCLUDED.account_login,
    account_id = EXCLUDED.account_id,
    account_type = EXCLUDED.account_type
RETURNING id, github_installation_id, account_login, account_id, account_type, created_at
`

type UpsertGitHubInstallationParams struct {
	GithubInstallationID string `json:"github_installation_id"`
	AccountLogin         string `json:"account_login"`
	AccountID            string `json:"account_id"`
	AccountType          string `json:"account_type"`
}

func (q *Queries) UpsertGitHubInstallation(ctx context.Context, arg UpsertGitHubInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGitHubInstallation,
		arg.GithubInstallationID,
		arg.AccountLogin,
		arg.AccountID,
		arg.AccountType,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.AccountType,
		&i.CreatedAt,
	)
	return i, err
}
