// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: builds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (project_id, status, commit_sha, commit_message)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at
`

type CreateBuildParams struct {
	ProjectID     pgtype.UUID `json:"project_id"`
	Status        string      `json:"status"`
	CommitSha     pgtype.Text `json:"commit_sha"`
	CommitMessage pgtype.Text `json:"commit_message"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRow(ctx, createBuild,
		arg.ProjectID,
		arg.Status,
		arg.CommitSha,
		arg.CommitMessage,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Logs,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteBuildsByProject = `-- name: DeleteBuildsByProject :exec
DELETE FROM builds WHERE project_id = $1
`

func (q *Queries) DeleteBuildsByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildsByProject, projectID)
	return err
}

const getBuildByCommitSHA = `-- name: GetBuildByCommitSHA :one
SELECT id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at FROM builds 
WHERE project_id = $1 AND commit_sha = $2
LIMIT 1
`

type GetBuildByCommitSHAParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	CommitSha pgtype.Text `json:"commit_sha"`
}

func (q *Queries) GetBuildByCommitSHA(ctx context.Context, arg GetBuildByCommitSHAParams) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByCommitSHA, arg.ProjectID, arg.CommitSha)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Logs,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getBuildByID = `-- name: GetBuildByID :one
SELECT id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at FROM builds WHERE id = $1
`

func (q *Queries) GetBuildByID(ctx context.Context, id pgtype.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getBuildByID, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Logs,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestBuildByProject = `-- name: GetLatestBuildByProject :one
SELECT id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at FROM builds 
WHERE project_id = $1 
ORDER BY created_at DESC 
LIMIT 1
`

func (q *Queries) GetLatestBuildByProject(ctx context.Context, projectID pgtype.UUID) (Build, error) {
	row := q.db.QueryRow(ctx, getLatestBuildByProject, projectID)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Logs,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listBuildsByProject = `-- name: ListBuildsByProject :many
SELECT id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at FROM builds 
WHERE project_id = $1 
ORDER BY created_at DESC 
LIMIT $2
`

type ListBuildsByProjectParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListBuildsByProject(ctx context.Context, arg ListBuildsByProjectParams) ([]Build, error) {
	rows, err := q.db.Query(ctx, listBuildsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Build{}
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Status,
			&i.CommitSha,
			&i.CommitMessage,
			&i.Logs,
			&i.ArtifactID,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildArtifact = `-- name: UpdateBuildArtifact :exec
UPDATE builds SET artifact_id = $2 WHERE id = $1
`

type UpdateBuildArtifactParams struct {
	ID         pgtype.UUID `json:"id"`
	ArtifactID pgtype.Text `json:"artifact_id"`
}

func (q *Queries) UpdateBuildArtifact(ctx context.Context, arg UpdateBuildArtifactParams) error {
	_, err := q.db.Exec(ctx, updateBuildArtifact, arg.ID, arg.ArtifactID)
	return err
}

const updateBuildStatus = `-- name: UpdateBuildStatus :one
UPDATE builds SET
    status = $2,
    completed_at = CASE WHEN $2 IN ('success', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, project_id, status, commit_sha, commit_message, logs, artifact_id, created_at, completed_at
`

type UpdateBuildStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateBuildStatus(ctx context.Context, arg UpdateBuildStatusParams) (Build, error) {
	row := q.db.QueryRow(ctx, updateBuildStatus, arg.ID, arg.Status)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.CommitSha,
		&i.CommitMessage,
		&i.Logs,
		&i.ArtifactID,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
