// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: build_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBuildLog = `-- name: CreateBuildLog :one
INSERT INTO build_logs (build_id, level, message)
VALUES ($1, $2, $3)
RETURNING id, build_id, level, message, timestamp
`

type CreateBuildLogParams struct {
	BuildID pgtype.UUID `json:"build_id"`
	Level   string      `json:"level"`
	Message string      `json:"message"`
}

func (q *Queries) CreateBuildLog(ctx context.Context, arg CreateBuildLogParams) (BuildLog, error) {
	row := q.db.QueryRow(ctx, createBuildLog, arg.BuildID, arg.Level, arg.Message)
	var i BuildLog
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Level,
		&i.Message,
		&i.Timestamp,
	)
	return i, err
}

type CreateBuildLogsBatchParams struct {
	BuildID pgtype.UUID `json:"build_id"`
	Level   string      `json:"level"`
	Message string      `json:"message"`
}

const deleteBuildLogsByBuild = `-- name: DeleteBuildLogsByBuild :exec
DELETE FROM build_logs WHERE build_id = $1
`

func (q *Queries) DeleteBuildLogsByBuild(ctx context.Context, buildID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBuildLogsByBuild, buildID)
	return err
}

const getBuildLogCount = `-- name: GetBuildLogCount :one
SELECT COUNT(*) FROM build_logs WHERE build_id = $1
`

func (q *Queries) GetBuildLogCount(ctx context.Context, buildID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBuildLogCount, buildID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBuildLogsByBuild = `-- name: GetBuildLogsByBuild :many
SELECT id, build_id, level, message, timestamp FROM build_logs 
WHERE build_id = $1 
ORDER BY timestamp ASC
`

func (q *Queries) GetBuildLogsByBuild(ctx context.Context, buildID pgtype.UUID) ([]BuildLog, error) {
	rows, err := q.db.Query(ctx, getBuildLogsByBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildLog{}
	for rows.Next() {
		var i BuildLog
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Level,
			&i.Message,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
