// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateBuildLogsBatch implements pgx.CopyFromSource.
type iteratorForCreateBuildLogsBatch struct {
	rows                 []CreateBuildLogsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBuildLogsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBuildLogsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BuildID,
		r.rows[0].Level,
		r.rows[0].Message,
	}, nil
}

func (r iteratorForCreateBuildLogsBatch) Err() error {
	return nil
}

func (q *Queries) CreateBuildLogsBatch(ctx context.Context, arg []CreateBuildLogsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"build_logs"}, []string{"build_id", "level", "message"}, &iteratorForCreateBuildLogsBatch{rows: arg})
}
