// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deployments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDeployment = `-- name: ActivateDeployment :one
UPDATE deployments SET status = 'active', activated_at = NOW()
WHERE id = $1
RETURNING id, project_id, build_id, status, activated_at
`

func (q *Queries) ActivateDeployment(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, activateDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.Status,
		&i.ActivatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id, build_id, status)
VALUES ($1, $2, $3)
RETURNING id, project_id, build_id, status, activated_at
`

type CreateDeploymentParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	BuildID   pgtype.UUID `json:"build_id"`
	Status    string      `json:"status"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.ProjectID, arg.BuildID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.Status,
		&i.ActivatedAt,
	)
	return i, err
}

const deactivateProjectDeployments = `-- name: DeactivateProjectDeployments :exec
UPDATE deployments SET status = 'inactive' WHERE project_id = $1
`

func (q *Queries) DeactivateProjectDeployments(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateProjectDeployments, projectID)
	return err
}

const deleteDeploymentsByProject = `-- name: DeleteDeploymentsByProject :exec
DELETE FROM deployments WHERE project_id = $1
`

func (q *Queries) DeleteDeploymentsByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeploymentsByProject, projectID)
	return err
}

const getActiveDeploymentByProject = `-- name: GetActiveDeploymentByProject :one
SELECT id, project_id, build_id, status, activated_at FROM deployments 
WHERE project_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveDeploymentByProject(ctx context.Context, projectID pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getActiveDeploymentByProject, projectID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.Status,
		&i.ActivatedAt,
	)
	return i, err
}

const getDeploymentByID = `-- name: GetDeploymentByID :one
SELECT id, project_id, build_id, status, activated_at FROM deployments WHERE id = $1
`

func (q *Queries) GetDeploymentByID(ctx context.Context, id pgtype.UUID) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeploymentByID, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.BuildID,
		&i.Status,
		&i.ActivatedAt,
	)
	return i, err
}

const listDeploymentsByProject = `-- name: ListDeploymentsByProject :many
SELECT id, project_id, build_id, status, activated_at FROM deployments 
WHERE project_id = $1 
ORDER BY activated_at DESC
`

func (q *Queries) ListDeploymentsByProject(ctx context.Context, projectID pgtype.UUID) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeploymentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deployment{}
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.Status,
			&i.ActivatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
