// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: env.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEnvVar = `-- name: DeleteEnvVar :exec
DELETE FROM environment_variables 
WHERE project_id = $1 AND key = $2
`

type DeleteEnvVarParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
}

func (q *Queries) DeleteEnvVar(ctx context.Context, arg DeleteEnvVarParams) error {
	_, err := q.db.Exec(ctx, deleteEnvVar, arg.ProjectID, arg.Key)
	return err
}

const deleteEnvVarsByProject = `-- name: DeleteEnvVarsByProject :exec
DELETE FROM environment_variables WHERE project_id = $1
`

func (q *Queries) DeleteEnvVarsByProject(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvVarsByProject, projectID)
	return err
}

const getEnvVar = `-- name: GetEnvVar :one
SELECT id, project_id, key, value, created_at, updated_at FROM environment_variables 
WHERE project_id = $1 AND key = $2
`

type GetEnvVarParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
}

func (q *Queries) GetEnvVar(ctx context.Context, arg GetEnvVarParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, getEnvVar, arg.ProjectID, arg.Key)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvVarsByProject = `-- name: GetEnvVarsByProject :many
SELECT id, project_id, key, value, created_at, updated_at FROM environment_variables 
WHERE project_id = $1 
ORDER BY key
`

func (q *Queries) GetEnvVarsByProject(ctx context.Context, projectID pgtype.UUID) ([]EnvironmentVariable, error) {
	rows, err := q.db.Query(ctx, getEnvVarsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvironmentVariable{}
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvVar = `-- name: UpsertEnvVar :one
INSERT INTO environment_variables (project_id, key, value)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, key) DO UPDATE SET
    value = EXCLUDED.value,
    updated_at = NOW()
RETURNING id, project_id, key, value, created_at, updated_at
`

type UpsertEnvVarParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	Key       string      `json:"key"`
	Value     string      `json:"value"`
}

func (q *Queries) UpsertEnvVar(ctx context.Context, arg UpsertEnvVarParams) (EnvironmentVariable, error) {
	row := q.db.QueryRow(ctx, upsertEnvVar, arg.ProjectID, arg.Key, arg.Value)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
