// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                    string           `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                string           `json:"user_id"`
	AccessToken           pgtype.Text      `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	IDToken               pgtype.Text      `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 pgtype.Text      `json:"scope"`
	Password              pgtype.Text      `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Build struct {
	ID            pgtype.UUID      `json:"id"`
	ProjectID     pgtype.UUID      `json:"project_id"`
	Status        string           `json:"status"`
	CommitSha     pgtype.Text      `json:"commit_sha"`
	CommitMessage pgtype.Text      `json:"commit_message"`
	Logs          pgtype.Text      `json:"logs"`
	ArtifactID    pgtype.Text      `json:"artifact_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	CompletedAt   pgtype.Timestamp `json:"completed_at"`
}

type BuildLog struct {
	ID        pgtype.UUID      `json:"id"`
	BuildID   pgtype.UUID      `json:"build_id"`
	Level     string           `json:"level"`
	Message   string           `json:"message"`
	Timestamp pgtype.Timestamp `json:"timestamp"`
}

type Deployment struct {
	ID          pgtype.UUID      `json:"id"`
	ProjectID   pgtype.UUID      `json:"project_id"`
	BuildID     pgtype.UUID      `json:"build_id"`
	Status      string           `json:"status"`
	ActivatedAt pgtype.Timestamp `json:"activated_at"`
}

type EnvironmentVariable struct {
	ID        pgtype.UUID      `json:"id"`
	ProjectID pgtype.UUID      `json:"project_id"`
	Key       string           `json:"key"`
	Value     string           `json:"value"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type GithubInstallation struct {
	ID                   pgtype.UUID      `json:"id"`
	GithubInstallationID string           `json:"github_installation_id"`
	AccountLogin         string           `json:"account_login"`
	AccountID            string           `json:"account_id"`
	AccountType          string           `json:"account_type"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
}

type Project struct {
	ID                   pgtype.UUID      `json:"id"`
	Name                 string           `json:"name"`
	GithubUrl            string           `json:"github_url"`
	RootDirectory        pgtype.Text      `json:"root_directory"`
	BuildCommand         string           `json:"build_command"`
	AppType              string           `json:"app_type"`
	Domain               pgtype.Text      `json:"domain"`
	Port                 pgtype.Int4      `json:"port"`
	GithubRepoID         pgtype.Text      `json:"github_repo_id"`
	GithubRepoFullName   pgtype.Text      `json:"github_repo_full_name"`
	GithubBranch         pgtype.Text      `json:"github_branch"`
	GithubInstallationID pgtype.Text      `json:"github_installation_id"`
	AutoDeploy           bool             `json:"auto_deploy"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
}

type Session struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	UserID    string           `json:"user_id"`
}

type User struct {
	ID            string           `json:"id"`
	Name          string           `json:"name"`
	Email         string           `json:"email"`
	EmailVerified bool             `json:"email_verified"`
	Image         pgtype.Text      `json:"image"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Verification struct {
	ID         string           `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
