// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    name, github_url, root_directory, build_command, app_type,
    domain, port, github_repo_id, github_repo_full_name, 
    github_branch, github_installation_id, auto_deploy
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at
`

type CreateProjectParams struct {
	Name                 string      `json:"name"`
	GithubUrl            string      `json:"github_url"`
	RootDirectory        pgtype.Text `json:"root_directory"`
	BuildCommand         string      `json:"build_command"`
	AppType              string      `json:"app_type"`
	Domain               pgtype.Text `json:"domain"`
	Port                 pgtype.Int4 `json:"port"`
	GithubRepoID         pgtype.Text `json:"github_repo_id"`
	GithubRepoFullName   pgtype.Text `json:"github_repo_full_name"`
	GithubBranch         pgtype.Text `json:"github_branch"`
	GithubInstallationID pgtype.Text `json:"github_installation_id"`
	AutoDeploy           bool        `json:"auto_deploy"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.GithubUrl,
		arg.RootDirectory,
		arg.BuildCommand,
		arg.AppType,
		arg.Domain,
		arg.Port,
		arg.GithubRepoID,
		arg.GithubRepoFullName,
		arg.GithubBranch,
		arg.GithubInstallationID,
		arg.AutoDeploy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getNextAvailablePort = `-- name: GetNextAvailablePort :one
SELECT COALESCE(MAX(port), 3000) + 1 AS next_port FROM projects WHERE port IS NOT NULL
`

func (q *Queries) GetNextAvailablePort(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextAvailablePort)
	var next_port int32
	err := row.Scan(&next_port)
	return next_port, err
}

const getProjectByDomain = `-- name: GetProjectByDomain :one
SELECT id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at FROM projects WHERE domain = $1
`

func (q *Queries) GetProjectByDomain(ctx context.Context, domain pgtype.Text) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByDomain, domain)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByGitHubRepo = `-- name: GetProjectByGitHubRepo :one
SELECT id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at FROM projects 
WHERE github_repo_id = $1 AND github_branch = $2 
LIMIT 1
`

type GetProjectByGitHubRepoParams struct {
	GithubRepoID pgtype.Text `json:"github_repo_id"`
	GithubBranch pgtype.Text `json:"github_branch"`
}

func (q *Queries) GetProjectByGitHubRepo(ctx context.Context, arg GetProjectByGitHubRepoParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByGitHubRepo, arg.GithubRepoID, arg.GithubBranch)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByPort = `-- name: GetProjectByPort :one
SELECT id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at FROM projects WHERE port = $1
`

func (q *Queries) GetProjectByPort(ctx context.Context, port pgtype.Int4) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByPort, port)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GithubUrl,
			&i.RootDirectory,
			&i.BuildCommand,
			&i.AppType,
			&i.Domain,
			&i.Port,
			&i.GithubRepoID,
			&i.GithubRepoFullName,
			&i.GithubBranch,
			&i.GithubInstallationID,
			&i.AutoDeploy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
    name = COALESCE($2, name),
    github_url = COALESCE($3, github_url),
    root_directory = COALESCE($4, root_directory),
    build_command = COALESCE($5, build_command),
    domain = COALESCE($6, domain),
    auto_deploy = COALESCE($7, auto_deploy),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, github_url, root_directory, build_command, app_type, domain, port, github_repo_id, github_repo_full_name, github_branch, github_installation_id, auto_deploy, created_at, updated_at
`

type UpdateProjectParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          pgtype.Text `json:"name"`
	GithubUrl     pgtype.Text `json:"github_url"`
	RootDirectory pgtype.Text `json:"root_directory"`
	BuildCommand  pgtype.Text `json:"build_command"`
	Domain        pgtype.Text `json:"domain"`
	AutoDeploy    pgtype.Bool `json:"auto_deploy"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.GithubUrl,
		arg.RootDirectory,
		arg.BuildCommand,
		arg.Domain,
		arg.AutoDeploy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GithubUrl,
		&i.RootDirectory,
		&i.BuildCommand,
		&i.AppType,
		&i.Domain,
		&i.Port,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.GithubBranch,
		&i.GithubInstallationID,
		&i.AutoDeploy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
